CREATE TABLE ENDERECOS(
ID_ENDERECO SERIAL NOT NULL,
RUA TEXT,
NUMERO INT,
BAIRRO TEXT,
CIDADE TEXT,
CEP VARCHAR(15),
ESTADO CHAR(2),
COMPLEMENTO TEXT,
PRIMARY KEY (ID_ENDERECO)
);

CREATE TABLE CLIENTES(
ID_CLIENTE SERIAL NOT NULL,
Nome VARCHAR(100),
CPF VARCHAR(25) NOT NULL,
RG VARCHAR(20) NOT NULL,
Telefone VARCHAR(20),
Email VARCHAR(100),
Data_Nasc DATE,
Login VARCHAR(100),
Senha VARCHAR(100),
FK_ENDERECO INT REFERENCES ENDERECOS(ID_ENDERECO),
PRIMARY KEY(CPF)
);

CREATE TABLE EMPRESAS(
CNPJ VARCHAR(40) NOT NULL PRIMARY KEY,
ENDERECO INT,
NOME VARCHAR(100),
TELEFONE VARCHAR(20),
EMAIL VARCHAR(100),
FOREIGN KEY (ENDERECO) REFERENCES ENDERECOS(ID_ENDERECO)
);

CREATE TABLE CARTAO(
CPF VARCHAR(25) NOT NULL,
NUMERO_CARTAO VARCHAR(25) NOT NULL,
VALIDADE_CARTAO DATE NOT NULL,
TIPO_CARTAO VARCHAR(100) NOT NULL,
SENHA_CARTAO VARCHAR(100) NOT NULL,
PRIMARY KEY(NUMERO_CARTAO),
FOREIGN  KEY (CPF) REFERENCES CLIENTES (CPF)
);

CREATE TABLE TRANSACAO(
ID_TRANSACAO SERIAL NOT NULL PRIMARY KEY,
CARTAO_TRANSACAO VARCHAR(50) NOT NULL,
VALOR MONEY,
CNPJ_TRANSACAO VARCHAR(40) NOT NULL,
DATA_TRANSACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN  KEY (CARTAO_TRANSACAO) REFERENCES CARTAO(Numero_Cartao),
FOREIGN  KEY (CNPJ_TRANSACAO) REFERENCES EMPRESAS (CNPJ)
);

CREATE TABLE CARTAO_NFC(
NFC_UID_USUARIO VARCHAR(40) NOT NULL PRIMARY KEY,
CPF_PROPRIETARIO VARCHAR(40)REFERENCES CLIENTES(CPF),
DATA_CRIACAO_CARTAO DATE
);

CREATE TABLE MAQUINA_DECODIFICADORA(
NFC_UID_MAQUINA VARCHAR(40) NOT NULL PRIMARY KEY,
CNPJ_PROPRIETARIO VARCHAR(40)REFERENCES EMPRESAS (CNPJ),
DATA_CRIACAO DATE
);

CREATE TABLE VIAGEM(
CODIGO_VIAGEM SERIAL NOT NULL PRIMARY KEY,
NUMERO_ONIBUS VARCHAR(10),
NOME_VIAGEM TEXT,
PLACA VARCHAR(12) NOT NULL,
FK_NFC_UID_MAQUINA VARCHAR(40) REFERENCES MAQUINA_DECODIFICADORA(NFC_UID_MAQUINA),
HORARIO_SAIDA TIME,
DIA_VIAGEM DATE
);

CREATE TABLE PASSAGEM(
ID_PASSAGEM SERIAL NOT NULL PRIMARY KEY,
FK_NFC_UID_USUARIO VARCHAR(40) REFERENCES CARTAO_NFC(NFC_UID_USUARIO),
FK_NFC_UID_MAQUINA VARCHAR(40) REFERENCES MAQUINA_DECODIFICADORA(NFC_UID_MAQUINA),
DATA_PASSAGEM DATE,
HORA_PASSAGEM TIME
);